# Generated by Django 3.0 on 2021-01-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverWfootball',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_wfootball',
                'managed': False,
            },
        ),
    ]
