# Generated by Django 3.0 on 2021-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_naverwfootball'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatFromList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'flat_form_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverBaseball',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_baseball',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverBasketball',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_basketball',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverEsports',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_esports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverFootball',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_football',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverGeneral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverGolf',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_golf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverVolleyball',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_bolleyball',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverWbaseball',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_wbaseball',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FlatFormList',
        ),
    ]
