# Generated by Django 3.0 on 2021-01-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210124_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatFromList',
        ),
        migrations.DeleteModel(
            name='NaverBaseball',
        ),
        migrations.DeleteModel(
            name='NaverBasketball',
        ),
        migrations.DeleteModel(
            name='NaverEsports',
        ),
        migrations.DeleteModel(
            name='NaverFootball',
        ),
        migrations.DeleteModel(
            name='NaverGeneral',
        ),
        migrations.DeleteModel(
            name='NaverGolf',
        ),
        migrations.DeleteModel(
            name='NaverVolleyball',
        ),
        migrations.DeleteModel(
            name='NaverWbaseball',
        ),
        migrations.DeleteModel(
            name='NaverWfootball',
        ),
    ]
