# Generated by Django 3.0 on 2021-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_flatfrom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsNews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('flatform', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'naver_sports_news',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DaumNews',
        ),
        migrations.DeleteModel(
            name='NaverNews',
        ),
    ]
