# Generated by Django 3.0 on 2021-01-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210126_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sportsnews',
            table='sports_news',
        ),
    ]
